export const SET_INPUT_TEXT = 'SET_INPUT_TEXT';
export const SET_GEOCODER_OPTIONS = 'SET_GEOCODER_OPTIONS';
export const SET_SHOULD_ZOOM = 'SET_SHOULD_ZOOM';
export const SET_CONTROLLER_ZOOM = 'SET_CONTROLLER_ZOOM';
export const RESET_GEOCODER = 'RESET_GEOCODER';
export const SET_RESET_GEOCODER = 'SET_RESET_GEOCODER';
