export const SET_BUSINESS_DETAILS = 'SET_BUSINESS_DETAILS';
export const SET_SOCIAL_MEDIA = 'SET_SOCIAL_MEDIA';
export const SET_FILES = 'SET_FILES';
export const RESET_MARKETPLACE = 'RESERT_MARKETPLACE';
export const RESET_MARKETPLACE_BUSINESS = 'RESET_MARKETPLACE_BUSINESS';
export const SET_OTHER_QUESTIONS = 'SET_OTHER_QUESTIONS';
export const SET_CONTACT_DETAILS = 'SET_CONTACT_DETAILS';
