export const SET_BUSINESS_DETAILS = 'SET_BUSINESS_DETAILS';
export const SET_SOCIAL_MEDIA = 'SET_SOCIAL_MEDIA';
export const BUSINESS_FILES = 'BUSINESS_FILES';
export const RESET_MARKETPLACE = 'RESERT_MARKETPLACE';
export const RESET_MARKETPLACE_BUSINESS = 'RESET_MARKETPLACE_BUSINESS';
