export const INITIAL_MARKETPLACE = {
  businessDetails: {
    name: '',
    address_1: '',
    address_2: '',
    phone: '',
    city: '',
    state: '',
    zipcode: '',
    sun_open: '',
    sun_close: '',
    mon_open: '',
    mon_close: '',
    tues_open: '',
    tues_close: '',
    wed_open: '',
    wed_close: '',
    thurs_open: '',
    thurs_close: '',
    fri_open: '',
    fri_close: '',
    sat_open: '',
    sat_close: '',
    website: '',
    facebook: '',
    twitter: '',
    email: '',
    instagram: '',
  },
  files: {
    media: null,
  }
};
